<script lang="ts">
  import { fadeIn } from '$lib/actions/animate';
</script>

<svelte:head>
  <title>Datenschutz | Steuerkanzlei am Bodensee</title>
  <meta name="description" content="Datenschutzerklärung der Steuerkanzlei Ill in Stockach, Singen und Radolfzell am Bodensee." />
</svelte:head>

<section class="py-16 bg-gray-50">
  <div class="container mx-auto px-4">
    <h1 
      class="text-4xl font-bold mb-8"
      use:fadeIn
    >
      Datenschutzerklärung
    </h1>
    
    <div 
      class="prose prose-lg max-w-none"
      use:fadeIn={{ delay: 200 }}
    >
        <h1 id="datenschutzerkl-rung">Datenschutzerklärung</h1>
        <h2 id="1-name-und-kontaktdaten-des-verantwortlichen">1. Name und Kontaktdaten des Verantwortlichen</h2>
        <p>Diese Datenschutzerklärung informiert über die Verarbeitung personenbezogener Daten auf der Kanzleiwebseite von:
        Verantwortlicher: Ursula Ill, Steuerkanzlei Ill, Oberhof 21, 78351 B.-Ludwigshafen, info@steuerkanzlei-ill.de, +49 7773 920967</p>
        <h2 id="2-umfang-und-zweck-der-verarbeitung-personenbezogener-daten">2. Umfang und Zweck der Verarbeitung personenbezogener Daten</h2>
        <h3 id="2-1-aufruf-der-webseite">2.1 Aufruf der Webseite</h3>
        <p>Beim Aufruf dieser Webseite WWW.STEUERKANZLEI-ILL.DE werden durch den Internet-Browser, den der Besucher verwendet, automatisch Daten an den Server dieser Webseite gesendet und zeitlich begrenzt in einer Protokolldatei (Logfile) gespeichert. Bis zur automatischen Löschung werden nachstehende Daten ohne weitere Eingabe des Besuchers gespeichert:</p>
        <p>IP-Adresse des Endgeräts des Besuchers, Datum und
        Uhrzeit des Zugriffs durch den Besucher, Name und
        URL der vom Besucher aufgerufenen Seite,Webseite, von der aus der Besucher auf die Kanzleiwebseite gelangt (sog. Referrer-URL),
        Browser und Betriebssystem des Endgeräts des Besuchers sowie der Name des vom Besucher verwendeten Access-Providers.
        Die Verarbeitung dieser personenbezogenen Daten ist gem. Art. 6 Abs. 1 Satz 1 Buchst. f) DSGVO gerechtfertigt. Die Kanzlei hat ein berechtigtes Interesse an der Datenverarbeitung zu dem Zweck,
        die Verbindung zur Webseite der Kanzlei zügig aufzubauen,
        eine nutzerfreundliche Anwendung der Webseite zu ermöglichen,
        die Sicherheit und Stabilität der Systeme zu erkennen und zu gewährleisten und
        die Administration der Webseite zu erleichtern und zu verbessern.
        Die Verarbeitung erfolgt ausdrücklich nicht zu dem Zweck, Erkenntnisse über die Person des Besuchers der Webseite zu gewinnen.</p>
        <h3 id="2-2-kontaktformular">2.2 Kontaktformular</h3>
        <p>Besucher können über ein Online-Kontaktformular auf der Webseite Nachrichten an die Kanzlei übermitteln. Um eine Antwort empfangen zu können, ist zumindest die Angabe einer gültigen E-Mail-Adresse erforderlich. Alle weiteren Angaben kann die anfragende Person freiwillig geben. Mit Absenden der Nachricht über das Kontaktformular willigt der Besucher in die Verarbeitung der übermittelten personenbezogenen Daten ein. Die Datenverarbeitung erfolgt ausschließlich zu dem Zweck der Abwicklung und Beantwortung von Anfragen über das Kontaktformular. Dies geschieht auf Basis der freiwillig erteilten Einwilligung gem. Art. 6 Abs. 1 Satz 1 Buchst. a) DSGVO. Die für die Benutzung des Kontaktformulars erhobenen personenbezogenen Daten werden automatisch gelöscht, sobald die Anfrage erledigt ist und keine Gründe für eine weitere Aufbewahrung gegeben sind (z. B. anschließende Beauftragung unserer Kanzlei).</p>
        <h2 id="3-weitergabe-von-daten">3. Weitergabe von Daten</h2>
        <p>Personenbezogene Daten werden an Dritte übermittelt, wenn</p>
        <p>nach Art. 6 Abs. 1 Satz 1 Buchst. a) DSGVO durch die betroffene Person ausdrücklich dazu eingewilligt wurde,
        die Weitergabe nach Art. 6 Abs. 1 Satz 1 Buchst. f) DSGVO zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist und kein Grund zur Annahme besteht, dass die betroffene Person ein überwiegendes schutzwürdiges Interesse an der Nichtweitergabe ihrer Daten hat,
        für die Datenübermittlung nach Art. 6 Abs. 1 Satz 1 Buchst. c) DSGVO eine gesetzliche Verpflichtung besteht, und/oder
        dies nach Art. 6 Abs. 1 Satz 1 Buchst. b) DSGVO für die Erfüllung eines Vertragsverhältnisses mit der betroffenen Person erforderlich ist.
        In anderen Fällen werden personenbezogene Daten nicht an Dritte weitergegeben.</p>
        <h2 id="4-cookies">4. Cookies</h2>
        <p>Auf der Webseite werden sog. Cookies eingesetzt. Das sind Datenpakete, die zwischen dem Server der Kanzleiwebseite und dem Browser des Besuchers ausgetauscht werden. Diese werden beim Besuch der Webseite von den jeweils verwendeten Geräten (PC, Notebook, Tablet, Smartphone etc.) gespeichert. Cookies können insoweit keine Schäden auf den verwendeten Geräten anrichten. Insbesondere enthalten sie keine Viren oder sonstige Schadsoftware. In den Cookies werden Informationen abgelegt, die sich jeweils im Zusammenhang mit dem spezifisch eingesetzten Endgerät ergeben. Die Kanzlei kann damit keinesfalls unmittelbar Kenntnis von der Identität des Besuchers der Webseite erhalten.
        Cookies werden nach den Grundeinstellungen der Browser größtenteils akzeptiert. Die Browsereinstellungen können so eingerichtet werden, dass Cookies entweder auf den verwendeten Geräten nicht akzeptiert werden, oder dass jeweils ein besonderer Hinweis erfolgt, bevor ein neuer Cookie angelegt wird. Es wird allerdings darauf hingewiesen, dass die Deaktivierung von Cookies dazu führen kann, dass nicht alle Funktionen der Webseite bestmöglich genutzt werden können.
        Der Einsatz von Cookies dient dazu, die Nutzung des Webangebots der Kanzlei komfortabler zu gestalten. So kann beispielsweise anhand von Session-Cookies nachvollzogen werden, ob der Besucher einzelne Seiten der Webseite bereits besucht hat. Nach Verlassen der Webseite werden diese Session-Cookies automatisch gelöscht.
        Zur Verbesserung der Benutzerfreundlichkeit werden temporäre Cookies eingesetzt. Sie werden für einen vorübergehenden Zeitraum auf dem Gerät des Besuchers gespeichert. Bei erneutem Besuch der Webseite wird automatisch erkannt, dass der Besucher die Seite bereits zu einem früheren Zeitpunkt aufgerufen hat und welche Eingaben und Einstellungen dabei vorgenommen wurden, um diese nicht wiederholen zu müssen.
        Der Einsatz von Cookies erfolgt außerdem, um die Aufrufe der Webseite zu statistischen Zwecken und zum Zwecke der Verbesserung des Angebotes zu analysieren. Diese Cookies ermöglichen es, bei einem erneuten Besuch automatisch zu erkennen, dass die Webseite bereits zuvor vom Besucher aufgerufen wurde. Hier erfolgt nach einer jeweils festgelegten Zeit eine automatische Löschung der Cookies.
        Die durch Cookies verarbeiteten Daten sind für die o. g. Zwecke zur Wahrung der berechtigten Interessen der Kanzlei nach Art. 6 Abs. 1 Satz 1 Buchst. f) DSGVO gerechtfertigt.</p>
        <h2 id="5-analyse-dienste-f-r-webseiten-tracking">5. Analyse-Dienste für Webseiten, Tracking</h2>
        <p>Wir nutzen auf unserer Webseite den Webseiten-Analysedienst für Webseiten von Google (Google Analytics).
        Rechtsgrundlage für die Verwendung der Analyse-Tools ist Art. 6 Abs. 1 Satz 1 Buchst. f) DSGVO. Die Webseitenanalyse liegt im berechtigten Interesse unserer Kanzlei und dient der statistischen Erfassung der Seitennutzung zur fortlaufenden Verbesserung unserer Kanzleiwebseite und des Angebots unserer Dienstleistungen.
        Google Analytics
        Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. („Google“). Die Benutzung erfolgt auf der Grundlage des Art. 6 Abs. 1 S. 1 lit. f. DSGVO. Google Analytics verwendet sog. „Cookies“, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Webseite durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung der Webseite wie</p>
        <p>Browser-Typ/-Version,
        verwendetes Betriebssystem,
        Referrer-URL (die zuvor besuchte Seite),
        Hostname des zugreifenden Rechners (IP-Adresse),
        Uhrzeit der Serveranfrage,
        werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Wir haben zudem auf dieser Webseite Google Analytics um den Code „anonymizeIP“ erweitert. Dies garantiert die Maskierung Ihrer IP-Adresse, sodass alle Daten anonym erhoben werden. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt.
        Im Auftrag des Betreibers dieser Website wird Google diese Information benutzen, um Ihre Nutzung der Webseite auszuwerten, um Reports über die Webseiten-Aktivitäten zusammenzustellen und um weitere mit der Webseiten-Nutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Webseitenbetreiber zu erbringen. Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall möglicherweise nicht sämtliche Funktionen dieser Webseite vollumfänglich werden nutzen können.
        Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Webseite bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: HTTP://TOOLS.GOOGLE.COM/DLPAGE/GAOPTOUT?HL=DE. Alternativ zum Browser-Add-On, insbesondere bei Browsern auf mobilen Endgeräten, können Sie die Erfassung durch Google Analytics zudem verhindern, indem Sie auf diesen Link klicken. Es wird ein Opt-Out-Cookie gesetzt, das die zukünftige Erfassung Ihrer Daten beim Besuch dieser Website verhindert. Der Opt-Out-Cookie gilt nur in diesem Browser und nur für unsere Website und wird auf Ihrem Gerät abgelegt. Löschen Sie die Cookies in diesem Browser, müssen Sie das Opt-Out-Cookie erneut setzen. [Anm. Hinweise zur Einbindung des Opt-Out-Cookie finden Sie unter: HTTPS://DEVELOPERS.GOOGLE.COM/ANALYTICS/DEVGUIDES/COLLECTION/GAJS/?HL=DE#DISABLE].
        Wir nutzen Google Analytics weiterhin dazu, Daten aus Double-Click-Cookies und auch AdWords zu statistischen Zwecken auszuwerten. Sollten Sie dies nicht wünschen, können Sie dies über den Anzeigenvorgaben-Manager (HTTP://WWW.GOOGLE.COM/SETTINGS/ADS/ONWEB/?HL=DE) deaktivieren.</p>
        <h2 id="6-plugins-sozialer-netzwerke-social-plugins-">6. Plugins sozialer Netzwerke (Social Plugins)</h2>
        <p>Auf unserer Kanzleiwebseite sind Plugins der nachstehenden sozialen Netzwerke eingebunden: Facebook.
        Rechtsgrundlage für den Einsatz von Social Plugins ist Art. 6 Abs. 1 Satz 1 Buchst. f) DSGVO. Ein berechtigtes Interesse unserer Kanzlei und Zweck des Einsatzes von Plugins sozialer Netzwerke ist es, unser Angebot einem breiten Publikum gegenüber bekanntzumachen. Die sozialen Netzwerke sind für den datenschutzkonformen Umgang mit den Daten ihrer Nutzer verantwortlich.</p>
        <p>Facebook
        Dieses Angebot verwendet Social Plugins (“Plugins”) des sozialen Netzwerkes facebook.com, welches von der Facebook Inc., 1601 S. California Ave, Palo Alto, CA 94304, USA betrieben wird (“Facebook”). Die Plugins sind an einem der Facebook Logos erkennbar (weißes „f“ auf blauer Kachel oder ein „Daumen hoch“-Zeichen) oder sind mit dem Zusatz “Facebook Social Plugin” gekennzeichnet. Die Liste und das Aussehen der Facebook Social Plugins kann hier eingesehen werden: HTTPS://DEVELOPERS.FACEBOOK.COM/DOCS/PLUGINS/.
        Wenn ein Nutzer eine Webseite dieses Angebots aufruft, die ein solches Plugin enthält, baut sein Browser eine direkte Verbindung mit den Servern von Facebook auf. Der Inhalt des Plugins wird von Facebook direkt an Ihren Browser übermittelt und von diesem in die Webseite eingebunden. Der Anbieter hat daher keinen Einfluss auf den Umfang der Daten, die Facebook mit Hilfe dieses Plugins erhebt und informiert die Nutzer daher entsprechend seinem Kenntnisstand:
        Durch die Einbindung der Plugins erhält Facebook die Information, dass ein Nutzer die entsprechende Seite des Angebots aufgerufen hat. Ist der Nutzer bei Facebook eingeloggt, kann Facebook den Besuch seinem Facebook-Konto zuordnen. Wenn Nutzer mit den Plugins interagieren, zum Beispiel den Like Button betätigen oder einen Kommentar abgeben, wird die entsprechende Information von Ihrem Browser direkt an Facebook übermittelt und dort gespeichert. Falls ein Nutzer kein Mitglied von Facebook ist, besteht trotzdem die Möglichkeit, dass Facebook seine IP-Adresse in Erfahrung bringt und speichert. Laut Facebook wird in Deutschland nur eine anonymisierte IP-Adresse gespeichert.
        Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch Facebook sowie die diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz der Privatsphäre der Nutzer, können diese den Datenschutz-Hinweisen von Facebook entnehmen: HTTPS://WWW.FACEBOOK.COM/ABOUT/PRIVACY/.
        Wenn ein Nutzer Facebook-Mitglied ist und nicht möchte, dass Facebook über dieses Angebot Daten über ihn sammelt und mit seinen bei Facebook gespeicherten Mitgliedsdaten verknüpft, muss er sich vor dem Besuch des Internetauftritts bei Facebook ausloggen.
        Weitere Einstellungen und Widersprüche zur Nutzung von Daten für Werbezwecke, sind innerhalb der Facebook-Profileinstellungen möglich: HTTPS://WWW.FACEBOOK.COM/SETTINGS?TAB=ADS oder über die US-amerikanische Seite HTTP://WWW.ABOUTADS.INFO/CHOICES/ oder die EU-Seite HTTP://WWW.YOURONLINECHOICES.COM/. Die Einstellungen erfolgen plattformunabhängig, d.h. sie werden für alle Geräte, wie Desktopcomputer oder mobile Geräte übernommen.</p>
        <p>Facebook Remarketing / Retargeting
        Auf unseren Seiten sind Remarketing-Tags des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert. Wenn Sie unsere Seiten besuchen, wird über die Remarketing-Tags eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt. Facebook erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben. Dadurch kann Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Die so erhaltenen Informationen können wir für die Anzeige von Facebook Ads nutzen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook erhalten. Weitere Informationen hierzu finden Sie in der Datenschutz-Erklärung von Facebook unter HTTPS://WWW.FACEBOOK.COM/ABOUT/PRIVACY/. Falls Sie keine Datenerfassung via Custom Audience wünschen, können Sie Custom Audiences hier deaktivieren.</p>
        <p>Konversionsmessung mit dem Besucheraktions-Pixel von Facebook
        Mit Ihrer Einwilligung setzen wir innerhalb unseres Internetauftritts den “Besucheraktions-Pixel” der Facebook Inc., 1601 S. California Ave, Palo Alto, CA 94304, USA (“Facebook”) ein. Mit dessen Hilfe können wir die Aktionen von Nutzern nachverfolgen, nach dem diese eine Facebook-Werbeanzeige gesehen oder geklickt haben. So können wir die Wirksamkeit der Facebook-Werbeanzeigen für statistische und marktforschungszwecke erfassen. Die so erfassten Daten sind für uns anonym, das heißt wir sehen nicht die personenbezogenen Daten einzelner Nutzer. Diese Daten werden jedoch von Facebook gespeichert und verarbeitet, worüber wir Sie entsprechend unserem Kenntnisstand unterrichten. Facebook kann diese Daten mit ihrem Facebookkonto verbinden und auch für eigene Werbezwecke, entsprechend Facebooks Datensverwendungsrichtlinie verwenden HTTPS://WWW.FACEBOOK.COM/ABOUT/PRIVACY/. Sie können Facebook sowie dessen Partnern das Schalten von Werbeanzeigen auf und außerhalb von Facebook ermöglichen. Es kann ferner zu diesen Zwecken ein Cookie auf Ihrem Rechner gespeichert werden.
        Diese Einwilligung darf nur von Nutzern, die älter als 13 Jahre alt sind erklärt werden. Falls Sie jünger sind, bitten wir, Ihre Erziehungsberechtigten um Rat zu fragen.</p>
        <h2 id="7-ihre-rechte-als-betroffene-person">7. Ihre Rechte als betroffene Person</h2>
        <p>Soweit Ihre personenbezogenen Daten anlässlich des Besuchs unserer Webseite verarbeitet werden, stehen Ihnen als „betroffene Person“ im Sinne der DSGVO folgende Rechte zu:</p>
        <h3 id="7-1-auskunft">7.1 Auskunft</h3>
        <p>Sie können von uns Auskunft darüber verlangen, ob personenbezogene Daten von Ihnen bei uns verarbeitet werden. Kein Auskunftsrecht besteht, wenn die Erteilung der begehrten Informationen gegen die Verschwiegenheitspflicht gem. § 57 Abs. 1 StBerG verstoßen würde oder die Informationen aus sonstigen Gründen, insbesondere wegen eines überwiegenden berechtigten Interesses eines Dritten, geheim gehalten werden müssen. Hiervon abweichend kann eine Pflicht zur Erteilung der Auskunft bestehen, wenn insbesondere unter Berücksichtigung drohender Schäden Ihre Interessen gegenüber dem Geheimhaltungsinteresse überwiegen. Das Auskunftsrecht ist ferner ausgeschlossen, wenn die Daten nur deshalb gespeichert sind, weil sie aufgrund gesetzlicher oder satzungsmäßiger Aufbewahrungsfristen nicht gelöscht werden dürfen oder ausschließlich Zwecken der Datensicherung oder der Datenschutzkontrolle dienen, sofern die Auskunftserteilung einen unverhältnismäßig hohen Aufwand erfordern würde und die Verarbeitung zu anderen Zwecken durch geeignete technische und organisatorische Maßnahmen ausgeschlossen ist. Sofern in Ihrem Fall das Auskunftsrecht nicht ausgeschlossen ist und Ihre personenbezogenen Daten von uns verarbeitet werden, können Sie von uns Auskunft über folgende Informationen verlangen:</p>
        <p>Zwecke der Verarbeitung,
        Kategorien der von Ihnen verarbeiteten personenbezogenen Daten,
        Empfänger oder Kategorien von Empfängern, gegenüber denen Ihre personenbezogenen Daten offen gelegt werden, insbesondere bei Empfängern in Drittländern,
        falls möglich die geplante Dauer, für die Ihre personenbezogenen Daten gespeichert werden oder, falls dies nicht möglich ist, die Kriterien für die Festlegung der Speicherdauer,
        das Bestehen eines Rechts auf Berichtigung oder Löschung oder Einschränkung der Verarbeitung der Sie betreffenden personenbezogenen Daten oder eines Widerspruchsrechts gegen diese Verarbeitung,
        das Bestehen eines Beschwerderechts bei einer Aufsichtsbehörde für den Datenschutz,
        sofern die personenbezogenen Daten nicht bei Ihnen als betroffene Person erhoben worden sind, die verfügbaren Informationen über die Datenherkunft,
        ggf. das Bestehen einer automatisierten Entscheidungsfindung einschließlich Profiling und aussagekräftige Informationen über die involvierte Logik sowie die Tragweite und angestrebten Auswirkungen automatisierter Entscheidungsfindungen,
        ggf. im Fall der Übermittlung an Empfänger in Drittländern, sofern kein Beschluss der EU-Kommission über die Angemessenheit des Schutzniveaus nach Art. 45 Abs. 3 DSGVO vorliegt, Informationen darüber, welche geeigneten Garantien gem. Art. 46 Abs. 2 DSGVO zum Schutze der personenbezogenen Daten vorgesehen sind.</p>
        <h3 id="7-2-berichtigung-und-vervollst-ndigung">7.2 Berichtigung und Vervollständigung</h3>
        <p>Sofern Sie feststellen, dass uns unrichtige personenbezogene Daten von Ihnen vorliegen, können Sie von uns die unverzügliche Berichtigung dieser unrichtigen Daten verlangen. Bei unvollständigen Sie betreffenden personenbezogenen Daten können sie die Vervollständigung verlangen.</p>
        <h3 id="7-3-l-schung">7.3 Löschung</h3>
        <p>Sie haben ein Recht auf Löschung („Recht auf Vergessenwerden“), sofern die Verarbeitung nicht zur Ausübung des Rechts auf freie Meinungsäußerung, des Rechts auf Information oder zur Erfüllung einer rechtlichen Verpflichtung oder zur Wahrnehmung einer Aufgabe, die im öffentlichen Interesse liegt, erforderlich ist und einer der nachstehenden Gründe zutrifft:
        Die personenbezogenen Daten sind für die Zwecke, für die sie verarbeitet wurden, nicht mehr notwendig.
        Die Rechtfertigungsgrundlage für die Verarbeitung war ausschließlich Ihre Einwilligung, welche Sie widerrufen haben.
        Sie haben Widerspruch gegen die Verarbeitung Ihrer personenbezogenen Daten eingelegt, die wir öffentlich gemacht haben.
        Sie haben Widerspruch gegen die Verarbeitung von uns nicht öffentlich gemachter personenbezogener Daten eingelegt und es liegen keine vorrangigen berechtigten Gründe für die Verarbeitung vor.
        Ihre personenbezogenen Daten wurden unrechtmäßig verarbeitet.
        Die Löschung der personenbezogenen Daten ist zur Erfüllung einer gesetzlichen Verpflichtung, der wir unterliegen, erforderlich.
        Kein Anspruch auf Löschung besteht, wenn die Löschung im Falle rechtmäßiger nicht automatisierter Datenverarbeitung wegen der besonderen Art der Speicherung nicht oder nur mit unverhältnismäßig hohem Aufwand möglich und Ihr Interesse an der Löschung gering ist. In diesem Fall tritt an die Stelle einer Löschung die Einschränkung der Verarbeitung.</p>
        <h3 id="7-4-einschr-nkung-der-verarbeitung">7.4 Einschränkung der Verarbeitung</h3>
        <p>Sie können von uns die Einschränkung der Verarbeitung verlangen, wenn einer der nachstehenden Gründe zutrifft:
        Sie bestreiten die Richtigkeit der personenbezogenen Daten. Die Einschränkung kann in diesem Fall für die Dauer verlangt werden, die es uns ermöglicht, die Richtigkeit der Daten zu überprüfen.
        Die Verarbeitung ist unrechtmäßig und Sie verlangen statt Löschung die Einschränkung der Nutzung Ihrer personenbezogenen Daten.
        Ihre personenbezogenen Daten werden von uns nicht länger für die Zwecke der Verarbeitung benötigt, die Sie jedoch zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigen.
        Sie haben Widerspruch gem. Art. 21 Abs. 1 DSGVO eingelegt. Die Einschränkung der Verarbeitung kann solange verlangt werden, wie noch nicht feststeht, ob unsere berechtigten Gründe gegenüber Ihren Gründen überwiegen.
        Einschränkung der Verarbeitung bedeutet, dass die personenbezogenen Daten nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder aus Gründen eines wichtigen öffentlichen Interesses verarbeitet werden. Bevor wir die Einschränkung aufheben, haben wir die Pflicht, Sie darüber zu unterrichten.</p>
        <h3 id="7-5-daten-bertragbarkeit">7.5 Datenübertragbarkeit</h3>
        <p>Sie haben ein Recht auf Datenübertragbarkeit, sofern die Verarbeitung auf Ihrer Einwilligung (Art. 6 Abs. 1 Satz 1 Buchst. a) oder Art. 9 Abs. 2 Buchst. a) DSGVO) oder auf einem Vertrag beruht, dessen Vertragspartei Sie sind und die Verarbeitung mithilfe automatisierter Verfahren erfolgt. Das Recht auf Datenübertragbarkeit beinhaltet in diesem Fall folgende Rechte, sofern hierdurch nicht die Rechte und Freiheiten anderer Personen beeinträchtigt werden: Sie können von uns verlangen, die personenbezogenen Daten, die Sie uns bereit gestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten. Sie haben das Recht, diese Daten einem anderen Verantwortlichen ohne Behinderung unserseits zu übermitteln. Soweit technisch machbar, können Sie von uns verlangen, dass wir Ihre personenbezogenen Daten direkt an einen anderen Verantwortlichen übermitteln.</p>
        <h3 id="7-6-widerspruch">7.6 Widerspruch</h3>
        <p>Sofern die Verarbeitung auf Art. 6 Abs. 1 Satz 1 Buchst. e) DSGVO (Wahrnehmung einer Aufgabe im öffentlichen Interesse oder in Ausübung öffentlicher Gewalt) oder auf Art. 6 Abs. 1 Satz 1 Buchst. f) DSGVO (berechtigtes Interesse des Verantwortlichen oder eines Dritten) beruht, haben Sie das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit gegen die Verarbeitung der Sie betreffenden personenbezogenen Daten Widerspruch einzulegen. Das gilt auch für ein auf Art. 6 Abs. 1 Satz 1 Buchst. e) oder Buchst. f) DSGVO gestütztes Profiling. Nach Ausübung des Widerspruchsrechts verarbeiten wir Ihre personenbezogenen Daten nicht mehr, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.
        Sie können jederzeit Widerspruch gegen die Verarbeitung der Sie betreffenden personenbezogenen Daten zu Zwecken der Direktwerbung einlegen. Das gilt auch für ein Profiling, das mit einer solchen Direktwerbung in Verbindung steht. Nach Ausübung dieses Widerspruchsrechts werden wir die betreffenden personenbezogenen Daten nicht mehr für Zwecke der Direktwerbung verwenden.
        Sie haben die Möglichkeit, den Widerspruch telefonisch, per E-Mail, oder an unsere zu Beginn dieser Datenschutzerklärung aufgeführte Postadresse unserer Kanzlei formlos mitzuteilen.</p>
        <h3 id="7-7-widerruf-einer-einwilligung">7.7 Widerruf einer Einwilligung</h3>
        <p>Sie haben das Recht, eine erteilte Einwilligung jederzeit mit Wirkung für die Zukunft zu widerrufen. Der Widerruf der Einwilligung kann telefonisch, per E-Mail, oder an unsere Postadresse formlos mitgeteilt werden. Durch den Widerruf wird die Rechtmäßigkeit der Datenverarbeitung, die aufgrund der Einwilligung bis zum Eingang des Widerrufs erfolgt ist, nicht berührt. Nach Eingang des Widerrufs wird die Datenverarbeitung, die ausschließlich auf Ihrer Einwilligung beruhte, eingestellt.</p>
        <h3 id="7-8-beschwerde">7.8 Beschwerde</h3>
        <p>Wenn Sie der Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten rechtswidrig ist, können Sie Beschwerde bei einer Aufsichtsbehörde für den Datenschutz einlegen, die für den Ort Ihres Aufenthaltes oder Arbeitsplatzes oder für den Ort des mutmaßlichen Verstoßes zuständig ist.</p>
        <h2 id="8-stand-und-aktualisierung-dieser-datenschutzerkl-rung">8. Stand und Aktualisierung dieser Datenschutzerklärung</h2>
        <p>Diese Datenschutzerklärung hat den Stand vom 25. Mai 2018. Wir behalten uns vor, die Datenschutzerklärung zu gegebener Zeit zu aktualisieren, um den Datenschutz zu verbessern und/oder an geänderte Behördenpraxis oder Rechtsprechung anzupassen.</p>
    </div>
  </div>
</section> 